# Create a jenkins job definition using  authentication
- name: Defining Jobs
  jenkins_job:
     - set_fact:
          complex_config: "{{ lookup('template', 'templates/{{item.template}}') }}"
          name: "{{item.name}}"
          password: "{{JENKINS_USERNAME_PASSWORD}}"
          url: "{{my_jenkins_url}}"
          user: "{{job_readers}}"
       when: "item.template is defined and item.name is defined"
       with_items: "{{my_jenkins_jobs}}"
       tags: ['Configure']
    - debug
        var: complex_config
